navikt/fp-formidling

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
- Midlertidig fiks ved å bytte om på rekkefølgen til to mapping-metode kall.
Den ene er deprecated og skal uansett fjernes.
> PFP-6163 SVP Innvilgelsebrev bugfix

- web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/app/konfig/ApplicationConfig.java
- web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/app/tjenester/ForvaltningRestTjeneste.java
Enkel forvaltnings-resttjeneste som i de andre applikasjonene. Skjelett + metode for å sette kronisk feilende tasks ferdig (der vi ikke venter på retting men har varslet bruker via saksbehandler)
BTW: Bruker man ikke fpfelles i fpformidling (ref tasks)?
> FIX TFP-495 forvaltningresttjeneste og metode for å sett tasks ferdig

- dokumentlager/domene/pom.xml
- dokumentlager/domene/src/test/resources/logback-test.xml
- dokumentproduksjon-klient/pom.xml
- dokumentproduksjon-klient/src/test/java/no/nav/foreldrepenger/melding/dokumentproduksjon/v2/DokumentProduksjonConsumerTest.java
- dokumentproduksjon-klient/src/test/java/no/nav/foreldrepenger/melding/dokumentproduksjon/v3/DokumentProduksjonConsumerTest.java
- domenetjenester/brevbestiller/pom.xml
- domenetjenester/brevbestiller/src/test/resources/logback-test.xml
- domenetjenester/fpsak/pom.xml
- domenetjenester/hendelse/pom.xml
- domenetjenester/organisasjon/pom.xml
- domenetjenester/poststed/pom.xml
- domenetjenester/tps/pom.xml
- integrasjon/dokdist-klient/pom.xml
- integrasjon/dokgen-klient/pom.xml
- integrasjon/journal-klient/pom.xml
- kafkatjenester/dokumenthendelse/pom.xml
- kafkatjenester/dokumenthistorikk/pom.xml
- kafkatjenester/dokumenthistorikk/src/test/java/kafkatjenester/historikk/DokumentHistorikkTjenesteTest.java
- kafkatjenester/dokumenthistorikk/src/test/resources/logback-test.xml
- kafkatjenester/kafkautil/pom.xml
- migreringer/src/main/resources/db/migration/defaultDS/1.0/V1.1_59__fjerne_kodelister.sql
- migreringer/src/test/resources/logback-test.xml
- pom.xml
- prosesstask/pom.xml
- prosesstask/src/test/resources/logback-test.xml
- web/pom.xml
- web/webapp/pom.xml
- web/webapp/src/test/resources/logback-test.xml
Den forrige må prodsettes før denne.
Har oppgradert til felles 2.4 og kjørt gjennom med maven-enforcer så det er litt endringer i poms.
> NOJIRA slett kodelister ny felles rydde etter enforce

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java
Når det gjelder fjerner av bestemSaksnummer for Infobrev gammel variant så tenker jeg vi avventer det til vi har lansert, altså ikke i samme PR
> TFP-4101 Lanserer infobrev til annen forelder

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/BeregningsresultatMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/BeregningsresultatMapperTest.java
Manglet håndtering av tilfellene hvor bruker har fått innvilget foreldrepenger, men utsetter fra start så ingen utbetaling og derav ingen refusjon.
> TFP-4501 Innvilget-foreldrepenger: manglet sjekk på ingenRefusjon.

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapperTest.java
Endret slik at stønadsperiodefom og tom kun mappes om datoene finnes siden de i enkelte tilfeller ikke har verdi. Null ble ikke godtatt av json når verdien var satt til required i schema.
> TFP-4582 Innvilgese foreldrepenger brev rettelse

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenBrevproduksjonTjeneste.java
Logger ved Json når forhåndsvisning feiler for saksnummer 148390054 for å finne ut hva som er årsaken. Json er anonymisert,
> Midlertidig logging for feilsøk

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UndermalInkluderingMapper.java
Lagt inn årsak 2038 - samtidig uttak i listen UTBETALING_ÅRSAKER som inkluderer innvilget undermalen om perioden har denne årsaken, og de andre kriteriene stemmer.
> TFP-4620 Rettelse samtidig uttak innv.foreldrepenger

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenBrevproduksjonTjeneste.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
For å forhindre at det sendes ut innvilgelsebrev foreldrepenger ved dødt barn når det finnes gjenlevende barn har vi lagt inn at det feiler. Når vi senere håndterer at ett av barna dør så må vi endre dette her også.
> TFP-4627 Feile hvis dødsdato og flere barn

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/avslagfp/ForeldrepengerAvslagDokumentdataMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
- domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/Behandlinger.java
- domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/uttak/KreverSammenhengendeUttakDto.java
- domenetjenester/poststed/src/main/java/no/nav/foreldrepenger/melding/poststed/KodeverkTjeneste.java
- integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/avslagfp/ForeldrepengerAvslagDokumentdata.java
- integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdata.java
Henter "krever-sammenhengende-uttak" fra fpsak slik at vi kan vite om en sak har fritt uttak eller ikke. Mapper verdien KreverSammenhengendeUttak på innvilgelse og avslag foreldrepenger.
> TFP-4622 Lagt til håndtering av fritt uttak

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/VarselOmRevurderingDokumentdataMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/VarselOmRevurderingDokumentdataMapperTest.java
- integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/VarselOmRevurderingDokumentdata.java
Lagt til parameteren kreverSammenhengendeUttak på mapping av VarselOmRevurderingDokumentdataMapper slik at brevet kan gi riktig tekst ved varslingsårsak ARBEIDS_I_STØNADSPERIODEN.
> TFP-4623 Lagt til håndtering av fritt uttak

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/VarselOmRevurderingDokumentdataMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/VarselOmRevurderingDokumentdataMapperTest.java
Rettet at det forsøkes å hente krever-sammenhengende-uttak for svangerskapspenger og engangsstønad når det bestilles varslingsbrev revurdering. Tjenesten gjelder kun foreldrepenger, og er derfor ikke tilgjengelig for es og svp.
> TFP-4656 Rettelse for varsling revurdering

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenBrevproduksjonTjeneste.java
Når noe er feil med et brev er det en fordel og ha json som blir generert tilgjengelig for å enklere kunne lokalisere hva som er feil.
> TFP-4568 lagrer json ved forhåndsvisning av brev

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java
FORELDREPENGER_OPPHØR var ved en feiltagelse fjernet fra DOKGEN_MALER_PROD som gjorde at dette brevet feilet
> FIX opphør foreldrepenger

- dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/familiehendelse/FamilieHendelse.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/EngangsstønadAvslagDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/EngangsstønadInnvilgelseDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/ForeldrepengerOpphørDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/ForlengetSaksbehandlingstidDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/SvangerskapspengerAvslagDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/VarselOmRevurderingDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/avslagfp/ForeldrepengerAvslagDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsesvp/SvangerskapspengerInnvilgelseDokumentdataMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapperTest.java
- integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/FamiliehendelseDtoMapper.java
- integrasjon/dtomapper/src/test/java/no/nav/foreldrepenger/melding/dtomapper/FamiliehendelseDtoMapperTest.java
Endret slik at dersom alle barna er døde settes dødsdato, ellers ikke. Det betyr at hvis det er gjenlevende barn så vil innvilgelse foreldrepenger trigges, og brev sendes ut uten forklaring om at flerbarnsdager blir trukket pga barn som dør. Saksbehandler må eventuelt overstyre dersom det er behov for ytterligere beskrivelse. Når løsningen har logikk for død kan vi også vurdere automatiske tekster
> TFP-4741 Endret håndtering av død innvilgelse fp

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapperTest.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapperTest.java
Endret OpphørPeriodeMapper for svp til å hente første og siste stønadsdato fra beregningsresultatet og ikke utttaket da uttaket i noen tilfeller vil være feil (feks hvis bruker dør). Antagelig blir det mer riktig å hente fra tilkjent ytelse i alle tilfeller.
> TFP-4791 Opphør svp - ved død

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapperTest.java
Fjerner perioder hvor dagsats er 0 når jeg henter første og siste dato fra beregningsresultat for å få med faktiske utbetalingsperioder.
> TFP-4791 Opphør svp - rettelse

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapper.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapperTest.java
I de tilfellene hvor saken ikke opphøres i uttak, og det ikke er utbetalt noe i saken, henter vi stønadsdatoFom og Tom fra det innvilgede uttaket. StønadsdatoFom og Tom benyttes i brevet ved opphør pga død og pga medlemsskap, ellers benyttes opphørsdato.
> TFP-4791 Rettelse svp opphør

- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapper.java
- domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMerger.java
- domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
- integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdata.java
- integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/Utbetalingsperiode.java
Dersom periodelisten inneholder 4095(MOR_TAR_IKKE_ALLE_UKENE) sjekkes det om det fortsatt er mulig å søke om dagene som er avslått. Det sjekkes ved å se om første uttaksdato etter før_fødsel + 3 måneder er før dagens dato. I såtilfelle settes nytt felt: morKanSøkeOmDagerFørFødsel til true.
> TFP-4778 Foreldrepenger innvilgelse

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
Rettet brist i logikk for å bestemme om tekst ved avslagsårsak 4095 skal vises eller ikke. Sjekker nå at dagens dato er før beregnet dato (beregnet dato = første dato i perioden som ikke er FØR_FØDSEL pluss 3 måneder).  Dersom det er tilfelle vil mor fortsatt kunne søke på avslått periode, og tekst vil vises i brevet.
> TFP-4778 FIX

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/BrevTaskProperties.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/DistribuerBrevTask.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjenesteTest.java
- integrasjon/dokdist/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/Dokdist.java
- integrasjon/dokdist/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/DokdistRestKlient.java
- integrasjon/dokdist/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/JerseyDokdistKlient.java
- integrasjon/dokdist/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/dto/DistribuerJournalpostRequest.java
- integrasjon/dokdist/src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/DokdistRestKlientTest.java
- integrasjon/journal/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjeneste.java
- integrasjon/journal/src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjenesteTest.java
Rettet at det ble journalført dokument med samme bestillingsUuid (ved verge). Dette førte til at en av dokumentene som ble sendt ut (enten til verge eller søker) ikke ble journalført, men brev ble distribuert. Pga spesialhåndtering av journalføring i fpfordel fanger vi ikke opp når journalføring sender 409 - conflict.
> TFP-4967 Bruker en unik referanse ved journalføring.

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/BehandlingNativeRestKlient.java
- web/src/main/resources/application.properties
En trailing / i app.properties gjorde først utslag og ble til fpsak//fpsak . Så enkoding av ? til %3F i UriBuilder
> Takle innkommende payload

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokdist/JavaDokdistRestKlient.java
Fører til at det blir Gosys-oppgave dersom dokdistfordeling sier 410 GONE for bruker som er død og det mangler dødsboadresse - noe som kan ta tid om gjenlevende sitter i uskiftet bo
> TFP-5250 Håndtere 410-respons

- .editorconfig
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/tjenester/ApplicationServiceStarterImpl.java
- web/src/main/java/no/nav/foreldrepenger/fpformidling/web/server/jetty/JettyServer.java
WEBINF_JAR_PATTERN pattern skanning vil ikke virker siden vi ikke benytter oss av WEB-INF/lib mappa
updateMetaData(...) er bare en hack til å få ting til å virke, og ideelt sett bør container skann finne ApplicationPath, WebListener, WebServlet og andre annotasjoner.
Det virker med CONTAINER_JAR_PATTERN som skanner gjennom java.class.path også og finner jar filer både ved lokalt kjøring og i docker.
> Forenkler jetty oppsett. Fikser jar scanning lokalt.

- .github/workflows/build.yml
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/DokArkivKlient.java
I NAIS sitt Kubernetes miljø ble det innført overgang fra standard namespace "default" til team namespace "team". Denne endringen påvirket også URL-ene for Kubernetes-tjenesteoppdagelse. Det ble slutt på oppretting av ressurser i default namespace den 29. september 2021.
Tidligere var en vanlig NAIS tjenesteoppdagelses-URL i Kubernetes som følger: "http://app.default/". Her refererte "default" til standardnavneområdet der tjenesten var plassert. Men nå, med innføringen av teamnavneområder, har URL-en blitt endret til "http://app.team/". Dette betyr at "team" erstatter "default" i URL-en og representerer det tilhørende teamet eller prosjektet som tjenesten tilhører.
For å lette denne overgangen ble det manuelt opprettet service redirects i default namespacet.
Vi ser at appen deres har en …
> Teamdokumenthandtering url oppdatering

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/SvangerskapspengerAvslagDokumentdataMapper.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/felles/SvpMapperUtil.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphorsvp/SvangerskapspengerOpphørDokumentdataMapper.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/felles/SvpMapperUtilTest.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphorsvp/SvangerskapspengerOpphørDokumentdataMapperTest.java
Henter siste dato fra tilkjent ytelse i stdet for fra uttak. Tar kun med de som har dagsat, legger på en dag og justerer eventuelt for helg. Uttak vil kunne inneholde flere opphørsårsaker og da vet vi ikke hvilken fra dato som blir riktig for tilfellet
> TFP-5487 Forsøker å utlede riktig opphørsdato for svp opphørsbrev

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphorfp/ForeldrepengerOpphørDokumentdataMapper.java
- web/src/test/resources/application-vtp.properties
Endret slik at ved barns død eller bruker er død henter vi siste utbetalingsdato fra siste innvilgede dato i stedet for å utlede dette fra opphørsdato. Dette vil bli feil dersom siste del av uttaket er avslått av endre grunner enn opphør.
> TFP-5536 ForeldrepengerOpphørDokumentdataMapper

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjeneste.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokumentMalUtleder.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/OpprettOppgaveTask.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjeneste.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjenesteTest.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokumentMalUtlederTest.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjenesteTest.java
- pom.xml
- Journalfører fritekstbrev med original brev type (VEDTAK_...)
- Oppretter historikk innslag med original brev type (det vises ikke lenger "Fritekstbrev" i fpsak men det som det faktisk er)  
- Bump deps
- Legger inn en prometheus counter på det som produseres.
> TFP-5592: Journalfører fritekstbrev med original brevkode.

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjeneste.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokumentMalUtleder.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjenesteTest.java
- brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokumentMalUtlederTest.java
- domene/src/main/java/no/nav/foreldrepenger/fpformidling/kodeverk/kodeverdi/DokumentMalType.java
- domene/src/main/java/no/nav/foreldrepenger/fpformidling/kodeverk/kodeverdi/DokumentMalTypeKode.java
Retter at vi ikke har noe å mappe fritekst brev som gjelder vedtak og endring i ytelsen til. I dag har vi ingen mal for denne type av endring. Saksbehandler overstyrer og lager et helt eget brev. Oppretter en malkode som kun benyttes for mapping og når vi lagrer journalposten. Malkoden kan brukes når vi oppretter et brev for denne type endring
> FIX Mapping av Fritekstmal til opprinnelig mal

- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjeneste.java
- brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/tjenester/forvaltning/ForvaltningRestTjeneste.java
Ny ForvaltningRestTjeneste for å generer brevdata i json format for en behandlingUuid. Det er kun mulig for vedtaksbrev. Tjenesten er ment brukt til feilanalyse  siden vi ikke lenger skal lagre brevdata når brev bestilles.
> TFP-4609 Legger til ForvaltningRestTjeneste

- pom.xml
- src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
- src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokumentMalUtleder.java
- src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/historikk/DokumentKvitteringTjeneste.java
- src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/historikk/SendKvitteringTask.java
- src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/BehandlingRestKlient.java
- src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/Behandlinger.java
- src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/historikk/DokumentKvitteringTjenesteTest.java
Malen lagres i fpsak i behandling_dokument_bestillt tabellen og henter derfra for historikk formål.
> TFP-5668: Tar i bruk V3 kvittering endepunkt som ikke lenger trenger dokument mal

- src/main/java/no/nav/foreldrepenger/fpformidling/domene/hendelser/HendelseRepository.java
- src/main/java/no/nav/foreldrepenger/fpformidling/felles/prosesstask/SlettGamleBestillingerTask.java
Sletter ferdige prosesstasker eldre enn et år og sletter bestillinger(hendelser) eldre enn 1 måned.
> TFP-5672 Sletter gamle tasks og bestillinger

- src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/oppgave/OppgaverTjeneste.java
Her opprettes kun ved manglende adresse. Kunne brukt type Behandle returpost
> TFP-5890 ikke angi opprettet av enhet for maskinelle oppgaver

- pom.xml
- src/main/java/no/nav/foreldrepenger/fpformidling/server/abac/AppPdpRequestBuilderImpl.java
Eksempel på at behandlingUuid er bærende og man må avgjøre om man stoler på at saksnummer matcher.
Eventuelt som nå - hente aktørId - eller hente saksnummer for behandlingUuid fra fpsak.
> TFP-5972 pdprequest-makeover

- pom.xml
- src/main/resources/logback.xml
Den forrige fungerte ikke helt i kubernetes - men fungerte helt greit lokalt. Men fant ikke ut hvorfor.
logback-syslog4j er dessverre ikke vedlikeholdt og det ville være greit med en alternativ løsning.
> revert: syslog endring
