navikt/fp-formidling

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/AvslagsårsakMapper.java

PFP-6849 Fpformidling: Mappe brev om Avslått foreldrepenger

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/behandling/Behandling.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/fagsak/Fagsak.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagEngangstønadBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/OpphørbrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BehandlingMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeMergerAvslag.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeMergerVerktøy.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/ÅrsakMapperAvslag.java

- Sammenslåing av like avslagsperioder i AvslagForeldrepengerMapper.
- Fikser nullpointer exception i AvslagEngangstønadBrevMapper.

PFP-6848, PFP-6849 Fpformidling: Mappe brev om Avslag

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/ÅrsakMapperAvslag.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/BeregningsgrunnlagDtoMapper.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/BeregningsresultatDtoMapper.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/UttakDtoMapper.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/sortering/PeriodeComparator.java

- Legger til sortering av perioder i mappingprosessen fra dto

FIX Sammenslåing av perioder:

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsresultatMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsresultatMapperTest.java
integrasjon/dokumentkontrakter/src/main/xsd-original/foreldrepenger_000061.xsd
integrasjon/dokumentkontrakter/src/main/xsd/foreldrepenger_000061.xsd

(~) Endrer stønadsperiodeFom/Tom til optional-felter
(+) XSD-oppdatering

PFP-7693 Innvilgelsesbrev:

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagForeldrepengerMapper.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlientImpl.java

(~) Optional beregningsgrunnlag
(~) Setter halvG til 0 hvis bg ikke finnes, siden verdien da uansett ikke
benyttes i brevet.

FIX AVSLFP

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/OpphørbrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsgrunnlagMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/ÅrsakMapperOpphør.java

(-) Duplikate avslagsårsaker.
(~) Optional uttaksresultat.
(~) Optional beregningsgrunnlag. Setter halvG til 0 hvis den ikke finnes.

FIX opphørsbrev

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/behandling/innsyn/InnsynDokument.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/BestillingType.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/repository/DokumentRepository.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/repository/DokumentRepositoryImpl.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/DokumentbestillingMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/api/BrevBestillerApplikasjonTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/BrevBestillerApplikasjonTjenesteImpl.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/task/ProduserBrevTask.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentMapperFeil.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/InnsynDtoMapper.java

Historikk innslag må gjøres for alle brev som blir sendt eks. når brev blir sendt for søker og verge

PFP-7805 Send brev for alle mottaker eks. søker og verge

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/DokumentFelles.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentFellesDataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentBestillerFeil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentBestillerTjenesteUtil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentXmlDataMapper.java
migreringer/src/main/resources/db/migration/defaultDS/1.0/V1.1_06__Tabeller_dokument_data_DDL.sql
web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/server/jetty/db/DatabaseScript.java

slettet felter
-nummerAvsenderEnhet
-signerendeBeslutterGeografiskEnhet

PFP-7804 Slette ubrukt felter i dokument_felles tabell

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/DokumentTypeId.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnhentOpplysningerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseEngangstønadBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BehandlingMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/MottattdokumentMapper.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlientImpl.java

- Henter klage mottattdato i klagebehandlinger
- Henter Endringssøknad dato når det gjelder endringssøknad
- Henter søknadsdato når det gjelder vanlige behandlinger/revurderinger

Oppdaterer måten vi setter søknadsdato på i brev om innhent opplysninger

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstmalBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeVerktøy.java

- Henter søknadsdato fra MottattdokumentMapper
- CDI workaround

NOJIRA EtterlysInntektsmeldingBrev:

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java

PFP-7212 Infobrev til far

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentMalUtleder.java
migreringer/src/main/resources/db/migration/defaultDS/1.0/V1.1_29__Fagsakytelsetype_SVP_i_kodeliste.sql

- Legger til fagsakytelseType 'SVP' i kodeliste
- SVP brev i DokumentMalUtleder

PFP-6163 Innvilgelse SVP

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstmalBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/AktivitetsMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsgrunnlagMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsresultatMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/beregning.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_en_GB.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_nb_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_nn_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/uttak.hbs
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapperTest.java

- Fikser punktliste
- Mapping fra beregningsgrunnlag

PFP-6163 Innvilgelsesbrev SVP

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervall.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/BrevMapperUtil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstmalBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeMergerSvp.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/brødtekst.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_en_GB.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_nb_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_nn_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/overskrift.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/felles/felles.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/felles/felles_en_GB.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/felles/felles_nb_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/felles/felles_nn_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/felles/overskrift.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/informasjontilannenforelder/brødtekst.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/informasjontilannenforelder/overskrift.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/beregning.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/brødtekst.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/utbetaling.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/uttak.hbs
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapperTest.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapperTest.java

- feilfiks og litt refaktorering i ift. threadsafety bl.a
PFP-8329 Etterlys Inntektsmelding brev:
- legger til støtte for SVP

PFP-6163 Innvilgelsesbrev SVP:

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervall.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/svp/SvpUttaksresultat.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/beregning.hbs

bugfikser:
- hentet arbeidsforhold fra feil sted i brevdata Map-objektet
- fikser IndexOutOfBoundsException

 PFP-6163 Innvilgelsesbrev SVP 

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/beregning/BeregningsresultatPeriode.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervall.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervallImpl.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/BrevMapperUtil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/AktivitetsMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/beregning.hbs
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/uttak.hbs
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapperTest.java

- Mapping av resterende felter, samt feilfiks på mapping av dato og dagsats

PFP-6163 Innvilgelsebrev SVP

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/Dato.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervall.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/typer/DatoIntervallImpl.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/UttakResultatPeriode.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/UttakResultatPeriodeAktivitet.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/UttakResultatPerioder.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/svp/SvpUttakResultatPeriode.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/svp/SvpUttaksresultat.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/BrevMapperUtil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseSvangerskapspengerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/OpphørbrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/BeregningsresultatMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/UttakMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeBeregner.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/sortering/PeriodeComparator.java

- Legger til getDato() i DatoIntervall igjen (burkes i beregning.hbs),
sammen med litt refaktorering

PFP-6163 SVP Innvilgelsebrev

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java

PFP-6163 SVP Innvilgelsebrev feilrettinger

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/uttak/svp/SvpUttakResultatPeriode.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java

- Maps som ikke kom med
- noen tilfeller med manglende datoformatering

PFP-6163 feilretting

---

integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/BeregningsresultatDtoMapper.java

- Case med privatperson som arbeidsgiver kræsjet fremdeles. Forsøker en
workaround.

PFP-8599 Legger til aktørID som ref. ved privatperson som arbeidsgiver

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentTypeMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentXmlDataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagEngangstønadBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AvslagForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/ForlengetSaksbehandlingstidBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstmalBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/HenleggBehandlingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnhentOpplysningerBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnsynskravSvarBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InntektsmeldingFørSøknadBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseEngangstønadBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InnvilgelseForeldrepengerMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageAvvistDokumentBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageOversendtKlageinstansBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageYtelsesvedtakOpphevetBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageYtelsesvedtakStadfestetBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/OpphørbrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/RevurderingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/UendretutfallBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/VedtakMedholdBrevMapper.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_en_GB.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_nb_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/innvilgelsesvangerskapspenger_nn_NO.properties
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapperTest.java
domenetjenester/brevbestiller/src/test/resources/dokumentmal/etterlysinntektsmelding/testdata.properties
domenetjenester/fpsak/pom.xml
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlientImpl.java

- Etablerer logging/catching av testdata i miljø, og prosedyre for å
reprodusere scenario som enhetstest lokalt.

PFP-8724 Verktøy for å logge og reprodusere testscenarier fra T4/Q1 som enhetstester lokalt

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/AktivitetsMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/domene/AktivitetsMapperTest.java

Graderte alltid først på lista.

TFP-316: Fikset sortering av graderte arbeidsforhold. 

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/beregningsgrunnlag/BeregningsgrunnlagPeriode.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/AktivitetsMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/BeregningsgrunnlagDtoMapper.java

- Fjerner avhengigheten til nye kodeverk for BeregnignsgrunnlagPeriode
ved å droppe initialiseringen. Bruker heller kode-stringen direkte.

TFP-585 fpformidling mangler kodeverk for gradering opphører

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/SvpMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/domene/sammenslåperioder/PeriodeBeregner.java

- Legger til filter slik at det kun er perioder med dagsats > 0 som
vises blant innvilgede

FIX TFP-589 SVP Brev

---

domenetjenester/brevbestiller/src/main/resources/dokumentmal/innvilgelsesvangerskapspenger/uttak.hbs

- endret slik at kulepunktliste ikke benyttes for enslige avslagperioder

FIX TFP-589 SVP Brev:

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageYtelsesvedtakStadfestetBrevMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageYtelsesvedtakStadfestetBrevMapperTest.java
integrasjon/dokumentkontrakter/src/main/xsd-original/foreldrepenger_000055.xsd
integrasjon/dokumentkontrakter/src/main/xsd/foreldrepenger_000055.xsd

TFP-918: (000055) Legger til SVP i brev for vedtak om stadfestelse

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/UendretutfallBrevMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/UendretutfallBrevMapperTest.java
integrasjon/dokumentkontrakter/src/main/xsd-original/foreldrepenger_000052.xsd
integrasjon/dokumentkontrakter/src/main/xsd/foreldrepenger_000052.xsd

TFP-922: (000052) Legger til SVP for ingen endring etter revurdering

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/task/ProduserBrevTaskProperties.java
domenetjenester/hendelse/src/main/java/no/nav/foreldrepenger/melding/hendelse/HendelseHandler.java

NOJIRA lagt til behandlingUUID som prop i prosestask

---

web/webapp/app-vtp.properties

Oppdaterer vtp propertis til å gå mot VTP sin kafka server.

feature/TPF-867: 

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentTypeMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/EtterlysInntektsmeldingBrevMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/InfoTilAnnenForelderBrevMapper.java
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_en_GB.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_nb_NO.properties
domenetjenester/brevbestiller/src/main/resources/dokumentmal/etterlysinntektsmelding/etterlysinntektsmelding_nn_NO.properties
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/OppsettForGjengivelseAvManuellTest.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlientImpl.java
pom.xml
web/webapp/pom.xml
web/webapp/src/main/java/no/nav/foreldrepenger/melding/sikkerhet/pdp/XacmlRequestBuilderTjenesteImpl.java
web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/app/pdp/PdpRequestBuilderImpl.java

utelater vedtaksformulering nederrst for INNLYS og INAFOR
oppdatert versjoner av felles og kontrakter

TFP-1377 ny formulering INNLYS, 

---

pom.xml
prosesstask/pom.xml
web/webapp/pom.xml
web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/server/jetty/AbstractJettyServer.java
web/webapp/src/test/java/no/nav/foreldrepenger/melding/web/server/jetty/JettyDevServer.java

Siste felles og prosesstask
Endring som fjerner scanned from multiple locations ved oppstart

FIX ny felles og fjerne scanned from multiple locs

---

kafkatjenester/dokumenthendelse/src/main/java/no/nav/foreldrepenger/melding/kafkatjenester/dokumentbestilling/KafkaReader.java
pom.xml
prosesstask/pom.xml
prosesstask/src/main/java/no/nav/vedtak/felles/prosesstask/batch/BatchTaskSchedueler.java
web/webapp/pom.xml

Tilbake til forrige felles. Som virket med kaka.

FIX forsøk revert felles for å løse kafka-issue

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/beregningsgrunnlag/Hjemmel.java
migreringer/src/main/resources/db/migration/defaultDS/1.0/V1.1_51__TFP-3166_hjemmel.sql

Hvorfor har man ikke gått over til enum og kodeverdi - som alle andre steder?

TFP-3316 ny hjemmel fra beregning

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
integrasjon/dokumentkontrakter/pom.xml
pom.xml
web/webapp/pom.xml
web/webapp/src/main/resources/web/swagger/index.html

Bumper flatten-maven-plugin og Swagger + legger til path-ignore i GA

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/anke/Anke.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/anke/AnkeVurdering.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/anke/AnkeVurderingOmgjør.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/klage/KlageFormkravResultat.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AnkeOmgjøreVedtakBrevMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/KlageAvvistBrevMapperTest.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/domene/KlageMapperTest.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/anke/AnkeVurderingResultatDto.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/anke/AnkebehandlingDto.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/klage/KlageFormkravResultatDto.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/klage/KlageVurderingResultatDto.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/klage/KlagebehandlingDto.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/klage/MottattKlagedokumentDto.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/AnkeDtoMapper.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/KlageDtoMapper.java

Prodsettes samtidig med sak og frontend

NOJIRA oppgrader ankedto parallellt med frontend og formidling

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AnkeOmgjøreVedtakBrevMapper.java

Prøver hente en null behandling

TFP-3845 nullsafe ankebrev

---

domenetjenester/brevbestiller/pom.xml
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/datamapper/brev/OppsettForGjengivelseAvManuellTest.java
pom.xml

Bruker Jackson i stedet for å dra inn ekstra Json-parser

NOJIRA bruk jackson til parsing av testdata

---

dokumentlager/domene/pom.xml
domenetjenester/brevbestiller/pom.xml
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/BrevbestillerFeil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/DokumentbestillingMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokprodBrevproduksjonTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DokumentXmlDataMapper.java
domenetjenester/tps/src/main/java/no/nav/foreldrepenger/pdl/PersondataTjeneste.java
integrasjon/journal-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/journal/OpprettJournalpostTjeneste.java
integrasjon/journal-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/journal/dto/Sak.java
pom.xml

Funksjonelle saksnummer - når de dukker opp

NOJIRA støtte for funksjonelle saksnummer + ny felles

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
domenetjenester/brevbestiller/src/test/resources/dokumentmal/innvilgelsesvangerskapspenger/testdata/scenario_at_fn_2.json
domenetjenester/brevbestiller/src/test/resources/dokumentmal/innvilgelsesvangerskapspenger/testdata/scenario_to_arbforhold.json
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/beregning/beregningsgrunnlag/BeregningsgrunnlagArbeidsforholdDto.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/BeregningsgrunnlagDtoMapper.java

Gjør på samme måte som uttak og br.

NOJIRA hente agnavn for beregningsgrunnlag

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentFellesDataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/DomeneobjektProvider.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/fagsak/FagsakDto.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/FagsakDtoMapper.java

Siste fase av å konvertere saksnummer Long -> String og slå sammen lenkene fagsak og fagsak-backend 
Forenkler verge-sjekken og reduserer lekkasje av lenke-navn

NOJIRA Endrer saksnummer til string

---

web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/app/exceptions/ConstraintViolationMapper.java
web/webapp/src/main/java/no/nav/foreldrepenger/melding/web/app/exceptions/FeltFeilDto.java
web/webapp/src/test/java/no/nav/foreldrepenger/melding/web/app/exceptions/GeneralRestExceptionMapperTest.java

Copy paste fra de andre prosjektene

Bedre logging ved constraint violation i web

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalType.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalTypeKode.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java

TFP-3532: Relanserer innhentingsbrevet i ny versjon.

TFP-4156: Lanserer forlenget saksbehandlingstid.

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMergerFellesTest.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/AnnenAktivitet.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/Arbeidsforhold.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/Næring.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/Prosent.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/Utbetalingsperiode.java
integrasjon/dokgen-klient/src/test/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/DokumentdataSerializationTest.java

TFP-2355: Innført value-objekt Prosent for innvilget FP Dokgen-klassene.

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/anke/Anke.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/AnkeOmgjøreVedtakBrevMapper.java
domenetjenester/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/anke/AnkeVurderingResultatDto.java
integrasjon/dtomapper/src/main/java/no/nav/foreldrepenger/melding/dtomapper/AnkeDtoMapper.java

prodsettes etter endringer i fpsak er i prod

Renamer felt for henting av påanket klagebehandling fra fpsak

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java

Det vil trigges for førstegangsbehandling uten gradering, avslag, ikke død, ikke samtidig uttak og kun språkvalg bokmål.

TFP-4272 Lansere begrenset innvilgelse foreldrepengerbrev fpdokgen.

---

web/src/main/java/no/nav/foreldrepenger/melding/web/app/tjenester/ForvaltningRestTjeneste.java

For tilfelle der ikke navngitte produkteiere har trikset med saksoppretting og inngående journalposter sil at det ikke finnes noen sak i arkivet - noe som trengs for dokprod

TFP-4512 forvaltningstjeneste for å opprette arkivsak til dokprod

---

dokumentproduksjon-klient/src/main/java/no/nav/foreldrepenger/melding/dokumentproduksjon/v2/SoapWebServiceFeil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokprodBrevproduksjonTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/ForhåndsvisningsException.java
web/src/main/java/no/nav/foreldrepenger/melding/web/app/exceptions/GeneralRestExceptionMapper.java

Logger ikke ForhåndsvisningsException. Foreløpig kun Opphør/SVP som fanges av den.
Har skilt andre dokprod-feil i innvilgelse/fp + resten (er vel kun avslag FP igjen)

Første tiltak forhåndsvisning for dokprod

---

dokumentlager/domene/pom.xml
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/konfig/BrevParametere.java
domenetjenester/fpsak/pom.xml
domenetjenester/organisasjon/src/main/java/no/nav/foreldrepenger/melding/organisasjon/VirksomhetTjeneste.java
integrasjon/kodeverk-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/kodeverk/KodeverkConsumer.java
kafkatjenester/dokumenthendelse/src/main/java/no/nav/foreldrepenger/melding/kafkatjenester/dokumentbestilling/DokumentbestillingStreamKafkaProperties.java
kafkatjenester/dokumenthistorikk/src/main/java/no/nav/foreldrepenger/melding/kafkatjenester/historikk/DokumentHistorikkinnslagProducer.java
migreringer/src/test/java/no/nav/foreldrepenger/melding/dbstoette/JpaExtension.java
pom.xml
web/pom.xml
web/src/main/java/no/nav/foreldrepenger/melding/web/app/pdp/PipRestKlient.java

Dekker dependabots for kontrakter, felles og hikari

Oppdater felles og kontrakter

---

web/src/main/java/no/nav/foreldrepenger/melding/web/app/tjenester/ForvaltningRestTjeneste.java

Så man ikke behøver erstatte behandlingUuid med uuid i Swagger

Mer brukervennlig versjon av Forvaltning.opprettsak

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdata.java

Lagt til 2 nye felter og mapping av disse for å håndtere dødt/døde barn i innvilget-foreldrepenger malen.

TFP-4561 Endringer InnvilgelseForeldrepengerDokumentDataMapper

---

domenetjenester/poststed/pom.xml

Kan anbefale mvn dependency:analyze for å bli klok på avhengigheter.

Fjernet ubrukt avhengighet

---

web/pom.xml
web/src/test/java/no/nav/foreldrepenger/melding/ArchitectureTest.java
web/src/test/java/no/nav/foreldrepenger/melding/TestArchitectureTest.java

Noen eksempler på ArchUnit-tester. Jeg gikk ikke så hardt inn på avhengigheter - 
men det er masse støtte for å legge inn tester på det.

ArchUnit tests for production and test classes

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenBrevproduksjonTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java

Rettet at sistedagAvSistePeriode er optional siden den ikke alltid finnes. Fjernet også midlertidig logging for feilsøk.

TFP-4285 Rettelse Innvilgelse foreldrepenger fpdokgen

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsefp/UtbetalingsperiodeMapperTest.java

Avklart følgende regler for prioritert utbetalingsgrad:
1. Dersom gradering og flere arbeidsforhold velges utbetalingsgrad fra det graderte arbeidsforholdet
2. Dersom flere arbeidsforhold velges den første utbetalingsgraden med verdi > 0

TFP-4592 Rettelse utbetalingsgrad innv.foreldrepenger

---

.deploy/dev-fss-teamforeldrepenger.json
.deploy/prod-fss-teamforeldrepenger.json

Bytter til autodiscovery slik at man blir uavhengig av ingress.

Autodiscovery isteden ingress for dokgen.

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/ForeldrepengerInfoTilAnnenForeldrerDokumentdataMapper.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/ForeldrepengerInfoTilAnnenForelderDokumentdata.java

Lagt til kreverSammenhengendeUttak for å skille på tekst for saker med fritt uttak og ikke i brevet

TFP-4414 Endret ForeldrepengerInfoTilAnnenForeldrerDokumentdataMapper

---

migreringer/src/main/resources/db/migration/defaultDS/1.0/V1.1_63__prosesstask-drop-type.sql
pom.xml
web/pom.xml
web/src/main/java/no/nav/foreldrepenger/melding/web/app/selftest/checks/DatabaseHealthCheck.java
web/src/test/java/no/nav/foreldrepenger/melding/web/app/selftest/checks/DatabaseHealthCheckTest.java

Det vil komme et par feilmeldinger ved prodsetting pga gammel livenessjekk - query mot prosess-task-type
Men det går helt greit.

ProsesstaskV3 del2 slett tabeller

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalType.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalTypeKode.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentMalUtleder.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/FritekstbrevDokumentdataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/innvilgelsesvp/SvangerskapspengerInnvilgelseDokumentdataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/datamapper/brev/FritekstBrevMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentMalUtlederTest.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/FritekstbrevDokumentdataMapperTest.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/FritekstbrevDokumentdata.java

Setter dere på PR så dere kan se over når dere er tilbake, men regner med å merge etterpå hvis jeg får noen til å godkjenne i Fpsak.

TFP-4747: Fritekstbrevet på Fp-dokgen.

---

dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/dokumentdata/DokumentTypeId.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalType.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalTypeKode.java
dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/vilkår/VilkårType.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokumentMalUtleder.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/SvangerskapspengerAvslagDokumentdataMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/felles/SvpMapperUtil.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørPeriodeMapper.java
domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapper.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/SvangerskapspengerAvslagDokumentdataMapperTest.java
domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/OpphørsperiodeMapperTest.java
integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/SvangerskapspengerAvslagDokumentdata.java

Nytt brev for avslag svangerskapspenger. Jeg har i tilegg lagt til SvpMapperUtil for å samle det som er felles for avslag og opphør på svp.

TFP-1022 Avslagsbrev for svangerskapspenger

---

domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapper.java

Endret slik at vi henter språkkode fra behandling

TFP-1024 Opphør svp

---

pom.xml

Greit å se over abakus og kalkulus også

Postgres patch + deps bump

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
.github/workflows/promote.yml
brevproduksjon/pom.xml
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
domene/pom.xml
integrasjon/dokdist/pom.xml
integrasjon/fpdokgen/pom.xml
integrasjon/fpdokgen/src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/DokumentdataSerializationTest.java
integrasjon/fpsak/pom.xml
integrasjon/journal/pom.xml
integrasjon/journal/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjeneste.java
integrasjon/organisasjon/pom.xml
integrasjon/pdl/pom.xml
integrasjon/pom.xml
kafkatjenester/dokumenthendelse/pom.xml
kafkatjenester/dokumenthendelse/src/main/java/no/nav/foreldrepenger/fpformidling/kafkatjenester/dokumentbestilling/DokumentHendelseDtoMapper.java
kafkatjenester/dokumenthendelse/src/test/java/no/nav/foreldrepenger/fpformidling/kafkatjenester/dokumentbestilling/KafkaReaderTest.java
kafkatjenester/dokumenthistorikk/pom.xml
kafkatjenester/pom.xml
migreringer/pom.xml
pom.xml
prosesstask/pom.xml
web/pom.xml
web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/tjenester/ForvaltningRestTjeneste.java
web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/tjenester/brev/BrevRestTjeneste.java

Ny /bestill REST endepunkt som gir mulighet til å bestille brev
Kvitter seg med bruk av flattened plugin.
Noe rydding i maven sha og changelist brukes ikke lenger.

Forbedringer - REST bestill tjeneste - ryddet flattened-plugin

---

domene/src/main/java/no/nav/foreldrepenger/fpformidling/uttak/svp/PeriodeIkkeOppfyltÅrsak.java
pom.xml
web/pom.xml

Manglet kode 8314 på vei inn til formidling

Manglende kode 8314

---

domene/src/main/java/no/nav/foreldrepenger/fpformidling/uttak/kodeliste/PeriodeResultatÅrsak.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/uttak/svp/PeriodeIkkeOppfyltÅrsak.java

De nye opphørsårsakene må inn i en metode

TFP-2944 legg inn periodeårsaker som opphørsårsaker

---

integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/behandling/familiehendelse/SøknadType.java

Expand-fase før omlegging av fpsak

Deserialisering av SøknadType som String

---

.github/workflows/build.yml
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/brevmal/BrevmalTjeneste.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/dto/behandling/familiehendelse/SøknadType.java
pom.xml
web/pom.xml

Forenkling av kontrakter
JsonValue i SøknadType

Siste fase overgang til jsonvalue

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
.github/workflows/promote.yml
pom.xml

Behandlende enhet hadde valid-pattern men validering ble aldri kjørt for Kafka (selvbetjening hadde enhet = null)

Oppdater kontrakter til versjon som validerer riktig

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/DomeneobjektProvider.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/AktivitetStatus.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/BGAndelArbeidsforhold.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/Beregningsgrunnlag.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/BeregningsgrunnlagAktivitetStatus.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/BeregningsgrunnlagPeriode.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/BeregningsgrunnlagPrStatusOgAndel.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/Hjemmel.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/beregningsgrunnlag/PeriodeÅrsak.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/opptjening/OpptjeningAktivitetType.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/typer/DatoIntervallImpl.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/virksomhet/Arbeidsgiver.java
integrasjon/fpsak/pom.xml
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/Behandlinger.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/JerseyBehandlinger.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/mapper/BeregningsgrunnlagDtoMapper.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/mapper/BeregningsgrunnlagV2DtoMapper.java
pom.xml

Kjører i en master/slave konfigurasjon i en try catch.

Fix: BeregningsgrunnlagV2

---

integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/BehandlingRestKlient.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/Behandlinger.java
integrasjon/fpsak/src/main/java/no/nav/foreldrepenger/fpsak/JerseyBehandlinger.java
kafkatjenester/dokumenthistorikk/pom.xml
kafkatjenester/dokumenthistorikk/src/main/java/no/nav/foreldrepenger/fpformidling/kafkatjenester/historikk/DokumentHistorikkTjeneste.java
kafkatjenester/dokumenthistorikk/src/test/java/kafkatjenester/historikk/DokumentHistorikkTjenesteTest.java

Kjører et par dager i dev først så bytter vi om i prod også.

TFP-4708: Brev kvittering gjennom REST

---

domene/pom.xml
pom.xml

Rydder domene test-jar

---

pom.xml
web/src/main/java/no/nav/foreldrepenger/fpformidling/web/server/jetty/JettyServer.java
web/src/test/java/no/nav/foreldrepenger/fpformidling/web/server/jetty/JettyDevServer.java

Fixen trenges kun for postgres baser - ellers er det bare å bumpe.

Bump fp-bom 0.3.4 - fix flyway 9.1

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/avslagfp/AvslåttPeriodeMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphørfp/ÅrsakMapperOpphør.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphørsvp/OpphørPeriodeMapper.java

3 skumle
private static Set<String> lovReferanser;

Trådsafe mapping av lovreferanser

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/DomeneobjektProvider.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/historikk/DokumentKvitteringTjeneste.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/BehandlingNativeRestKlient.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/JournalpostNativeRestKlient.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/journal/OpprettJournalpostTjeneste.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/pdl/PersondataTjeneste.java
pom.xml
web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/pdp/AppPdpRequestBuilderImpl.java
web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/pdp/PipRestKlient.java

Har ikke sett på de 3 klientene som allerede er native java. 
Oppgave bør hentes fra felles, eller manglende funksjonalitet legges inn i felles
Alle mangler timeout -> kan gi litt uforutsigbar oppførsel - opptil plattformen om den henger evig eller timer veldig fort ut.

Native hhtpclient for rest

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/EngangsstønadAvslagDokumentdataMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/DomeneobjektProvider.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/Behandlinger.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/BehandlingDto.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/BehandlingDtoMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/VilkårDtoMapper.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/EngangsstønadAvslagDokumentdataMapperTest.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/behandling/Behandling.java

Forenkle ettersom vilkår er med i BehandlingDto fra backend

Vilkår er med i behandlingDto til frontend

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsesvp/AvslagsperiodeMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/innvilgelsesvp/Avslagsperiode.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsesvp/AvslagsperiodeMapperTest.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsesvp/SvangerskapspengerInnvilgelseDokumentdataMapperTest.java

Endret mapping av Avslagsperiode til å ha med informasjon om arbeidsgiver slik at vi kan få ut rett tekst ved opphold i ett av flere arbeidsforhold

TFP-2836 - Svp innnvilgelsbrev

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/avslagfp/ForeldrepengerAvslagDokumentdataMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/avslagfp/ForeldrepengerAvslagDokumentdata.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/avslagfp/ForeldrepengerAvslagDokumentdataMapperTest.java

Lagt til om avslaget gjelder mor for å kunne gi tekst om mulig rett til engangsstønad for visse avslagsårsaker

TFP-3575 ForeldrepengerAvslagDokumentdata endring

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphorfp/ForeldrepengerOpphørDokumentdataMapper.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/ForeldrepengerOpphørDokumentdataMapperTest.java

Rettet feil med opphørsdato i de tilfellene hvor perioden før opphøret også var avslått, men ikke opphørt.

TFP-5536 ForeldrepengerOpphørDokumentdataMapper

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/KlageAvvistDokumentdata.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/KlageAvvistDokumentdataMapperTest.java

https://github.com/navikt/fp-dokgen/pull/698

TFP-4871 endret tittel på avvist klagebrev for ikke klager på vedtak

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/UtbetalingsperiodeMapper.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/UtbetalingsperiodeMerger.java
brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/innvilgelsefp/Arbeidsforhold.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/UtbetalingsperiodeMergerTest.java
brevproduksjon/src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/DokumentdataSerializationTest.java
domene/src/main/java/no/nav/foreldrepenger/fpformidling/klage/KlageAvvistÅrsak.java

Endret slik at vi mapper brutto inntekt inkludert naturalytelse om naturalytelse finnes (avkortet mappes til dette i fpsak).

TFP-2175 Endring naturalytelse foreldrepenger-innvilgelse

---

brevproduksjon/src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/pdl/PersondataTjeneste.java
lokalutvikling/docker-compose.yml

Lurer noe på om man ikke skulle bruke Navn.gyldigFraOgMed() istedenfor bare bruke .findFirst() men så frister det ikke veldig å parse en String til DateTime for å finne det gjeldende navnet.

Fikser navn i brevet til Fornavn Mellomnavn Etternavn

---

web/src/main/java/no/nav/foreldrepenger/fpformidling/web/app/tjenester/brev/BrevRestTjeneste.java
web/src/main/resources/application-prod-fss.properties

Må prodsettes etter https://github.com/navikt/fp-formidling/pull/2493 + 2 min

TFP-5665: Bytter basen om til den nye postgres 15 basen.

---

src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/HenleggeDokumentdataMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/KlageOversendtDokumentdataMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/felles/BrevMapperUtil.java
src/main/java/no/nav/foreldrepenger/fpformidling/domene/behandling/Behandling.java
src/main/java/no/nav/foreldrepenger/fpformidling/domene/hendelser/DokumentHendelse.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/HenleggelseDokumentdata.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/felles/FellesDokumentdata.java
src/main/java/no/nav/foreldrepenger/fpformidling/tjenester/DokumentHendelseDtoMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/tjenester/forvaltning/ForvaltningRestTjeneste.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjenesteTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/ForeldrepengerAnnullertDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/ForeldrepengerOpphørDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/ForlengetSaksbehandlingstidDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/FritekstbrevDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/HenleggeDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/IngenEndringDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/InnhenteOpplysningerDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/KlageAvvistDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/KlageOmgjortDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/KlageOversendtDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/SvangerskapspengerAvslagDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/VarselOmRevurderingDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/avslagfp/ForeldrepengerAvslagDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/ikkesokt/IkkeSøktDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsesvp/SvangerskapspengerInnvilgelseDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/opphorsvp/SvangerskapspengerOpphørDokumentdataMapperTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/DokumentdataSerializationTest.java

Bør sees i sammenheng med følgende endring i fp-dokgen https://github.com/navikt/fp-dokgen/pull/729

TFP-5696: Rydder behandlende enhet siden alle brev skal sendes av NFP.

---

src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/SvangerskapspengerAvslagDokumentdataMapper.java

https://github.com/navikt/fp-dokgen/pull/738

Sender fritekst videre til dokgen i avslagsbrev svp

---

src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/EtterlysInntektsmeldingDokumentdataMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/tjenester/DomeneobjektProvider.java
src/main/java/no/nav/foreldrepenger/fpformidling/domene/inntektarbeidytelse/ArbeidsforholdInntektsmelding.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/EtterlysInntektsmeldingDokumentdata.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/Behandlinger.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/ArbeidsforholdInntektsmeldingDtoMapper.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/EtterlysInntektsmeldingDokumentdataMapperTest.java

TFP-5719 Endring av brevet som etterlyser inntektsmelding.

---

src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/BehandlingDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/BehandlingsresultatDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/BehandlingÅrsakDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/familiehendelse/SøknadType.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/klage/KlageFormkravResultatDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/klage/KlageVurderingResultatDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/klage/KlagebehandlingDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/klage/MottattKlagedokumentDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/KlageDtoMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/SøknadDtoMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/VilkårDtoMapper.java

Fix: Mer rydding i kontrakten fpsak <-> formidling

---

src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdataMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/domene/behandling/Behandling.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/dokgen/dto/innvilgelsefp/ForeldrepengerInnvilgelseDokumentdata.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/dto/behandling/BehandlingDto.java
src/main/java/no/nav/foreldrepenger/fpformidling/integrasjon/fpsak/mapper/BehandlingDtoMapper.java

https://github.com/navikt/fp-dokgen/pull/770

TFP-5732 utvidet innvilgesbrev fp med medlemskap opphørsårsak

---

pom.xml
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/DokgenBrevproduksjonTjeneste.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/felles/SvpMapperUtil.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/BrevTaskProperties.java
src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/DistribuerBrevTask.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/bestiller/BrevBestillerTjenesteTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/DistribuerBrevTaskTest.java
src/test/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/task/OpprettOppgaveTaskTest.java

Mangler saksnummer i request for å kunne sette i bestillingtask

Sett saksnummer i prosesstask

---

Dockerfile
pom.xml
src/main/resources/logback.xml

+ fjerner handlebars som ikke brukes til noe i formidling.

chore: forenkler Dockerfile oppsett som er flyttet til baseimage

---

src/main/java/no/nav/foreldrepenger/fpformidling/server/abac/AppPdpRequestBuilderImpl.java
src/main/java/no/nav/foreldrepenger/fpformidling/server/abac/PipRestKlient.java

Merges etter PR i fpsak. Forarbeide til større endring i felles.

TFP-5972 innledende omlegging før ny felles

---

src/main/java/no/nav/foreldrepenger/fpformidling/brevproduksjon/mapper/innvilgelsefp/BeregningsgrunnlagMapper.java
src/main/java/no/nav/foreldrepenger/fpformidling/domene/beregningsgrunnlag/AktivitetStatus.java

Legger til spesialhåndtering når det finnes andel Arbeid under aap for å få riktig tekst om det er fastsatt et inntektsbeløp på denne andelen.

TFP-6286 innvilgesbrev foreldrepenger - aap praksiskendring
